# Generated by Django 6.0.5 on 2026-05-29 10:00

import account.models
import django.utils.crypto
import django.utils.timezone
import django_countries.fields
import functools
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=256)),
                ('last_name', models.CharField(blank=True, max_length=256)),
                ('company_name', models.CharField(blank=True, max_length=256)),
                ('street_address_1', models.CharField(blank=True, max_length=256)),
                ('street_address_2', models.CharField(blank=True, max_length=256)),
                ('city', models.CharField(blank=True, max_length=256)),
                ('city_area', models.CharField(blank=True, max_length=128)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('country_area', models.CharField(blank=True, max_length=128)),
                ('validation_skipped', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('restricted_access_to_channels', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
            },
            managers=[
                ('objects', account.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=256)),
                ('last_name', models.CharField(blank=True, max_length=256)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_confirmed', models.BooleanField(default=True)),
                ('last_confirm_email_request', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('last_password_reset_request', models.DateTimeField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user-avatars')),
                ('jwt_token_key', models.CharField(default=functools.partial(django.utils.crypto.get_random_string, length=12), max_length=12)),
                ('language_code', models.CharField(choices=[('af', 'Afrikaans'), ('af-na', 'Afrikaans (Namibia)'), ('af-za', 'Afrikaans (South Africa)'), ('en', 'English'), ('xh', 'Xhosa'), ('xh-za', 'Xhosa (South Africa)'), ('en-za', 'English (South Africa)'), ('nd', 'North Ndebele'), ('nd-zw', 'North Ndebele (Zimbabwe)'), ('zu', 'Zulu'), ('zu-za', 'Zulu (South Africa)')], default='en', max_length=35)),
                ('search_document', models.TextField(blank=True, default='')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('number_of_orders', models.PositiveIntegerField(db_default=0, default=0)),
            ],
            options={
                'ordering': ('email',),
                'permissions': (('manage_users', 'Manage customers.'), ('manage_staff', 'Manage staff.'), ('impersonate_user', 'Impersonate user.')),
            },
        ),
    ]
