# Generated by Django 6.0.5 on 2026-06-10 19:05

import django.db.models.deletion
import django.utils.timezone
import orders.models
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_modelwithmetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(default=orders.models.get_order_number, editable=False, unique=True)),
                ('use_old_id', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('unconfirmed', 'Unconfirmed'), ('unfulfilled', 'Unfulfilled'), ('partially fulfilled', 'Partially fulfilled'), ('partially_returned', 'Partially returned'), ('returned', 'Returned'), ('fulfilled', 'Fulfilled'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='unfulfilled', max_length=32)),
                ('authorize_status', models.CharField(choices=[('none', 'The funds are not authorized'), ('partial', "The funds that are authorized and charged don't cover fully the order's total"), ('full', "The funds that are authorized and charged fully cover the order's total")], db_index=True, default='none', max_length=32)),
                ('charge_status', models.CharField(choices=[('none', 'The order is not charged.'), ('partial', 'The order is partially charged'), ('full', 'The order is fully charged'), ('overcharged', 'The order is overcharged')], db_index=True, default='none', max_length=32)),
                ('language_code', models.CharField(choices=[('af', 'Afrikaans'), ('af-na', 'Afrikaans (Namibia)'), ('af-za', 'Afrikaans (South Africa)'), ('en', 'English'), ('xh', 'Xhosa'), ('xh-za', 'Xhosa (South Africa)'), ('en-za', 'English (South Africa)'), ('nd', 'North Ndebele'), ('nd-zw', 'North Ndebele (Zimbabwe)'), ('zu', 'Zulu'), ('zu-za', 'Zulu (South Africa)')], default='en', max_length=35)),
                ('tracking_client_id', models.CharField(blank=True, editable=False, max_length=36)),
                ('draft_save_billing_address', models.BooleanField(blank=True, null=True)),
                ('draft_save_shipping_address', models.BooleanField(blank=True, null=True)),
                ('user_email', models.EmailField(blank=True, default='', max_length=254)),
                ('origin', models.CharField(choices=[('checkout', 'Checkout'), ('draft', 'Draft'), ('reissue', 'Reissue'), ('bulk_create', 'Bulk create')], max_length=32)),
                ('currency', models.CharField(max_length=3)),
                ('shipping_method_name', models.CharField(blank=True, default=None, editable=False, max_length=255, null=True)),
                ('collection_point_name', models.CharField(blank=True, default=None, editable=False, max_length=255, null=True)),
                ('shipping_price_net_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), editable=False, max_digits=20)),
                ('shipping_price_net', models.FloatField()),
                ('shipping_price_gross_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), editable=False, max_digits=20)),
                ('shipping_price_gross', models.FloatField()),
                ('shipping_price', models.FloatField()),
                ('base_shipping_price_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=20)),
                ('shipping_tax_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('shipping_tax_class_name', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_address', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.address')),
                ('original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('shipping_address', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='account.user')),
            ],
        ),
    ]
